import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/shadcn-studio/blocks/navbar-component-01/navbar-component-01";
import Footer from "@/src/user-component/footer.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigationData = [
  {
    title: 'Home',
    href: '/'
  },
  {
    title: 'About Us',
    href: 'about-us'
  },
  {
    title: 'Portofolio',
    href: '/portofolio'
  },
  {
    title: 'Contacts',
    href: '/contacts'
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar navigationData={navigationData} />
        <div className="bg-[#E6E6E6] min-h-screen">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
